Feature/system controller
liqidinc/liqid-go pull request #5
Opened 2021-05-25 21:05 UTC by kyle-co

2021-05-25 21:11 UTC, kyle-co commented
I'll take care of the linting errors, but letting this soak for an hour so folks have a chance to see the `golangci-lint` GitHub Action automatically annotating PRs with problem lines of code.

2021-05-25 21:18 UTC, kyle-co commented on README.md
Added formatting, another section for contributions, and link to licensing.

2021-05-25 21:19 UTC, kyle-co commented on liqid.go
>  	}
I could use some feedback on this -- does this seem like a sensible way to handle it? log & return an error vs exit non-zero.

2021-05-25 21:21 UTC, kyle-co commented on liqid.go
> +	return resp, err
This was all boilerplate I removed from individual SDK wrappers. Some focused feedback here would be good. 

Any better logging idioms? I'm sure there's a way to do this in a more aesthetically pleasing way, like a switch.

2021-05-25 21:21 UTC, kyle-co commented on sshcontroller.go
> +	resp, err := client.Do(req)
Refactors to handle the new `client.Do` that was abstracted into the LiqidClient in liqid.go.

2021-05-25 21:23 UTC, kyle-co commented on sshcontroller.go
> +	return &ssh, err
I'm tempted to return this struct by value vs by reference. Thoughts?

2021-05-25 21:25 UTC, kyle-co commented on systemcontroller.go
> +	_, err = client.Do(req)
Programmatically, I have decided to throw out the response, since it is already logged in the `client.Do` function. If SDK consumers want to peel apart the responses, they can use that function directly. This should programmatically be simple. Do a thing, and get a thing and/or error.

2021-05-25 21:27 UTC, kyle-co commented on systemcontroller.go
> +	req.Header.Set("Content-Length", "0")
I am unsure of whether this is required, but I saw it was recommended to pass `Content-Length` of `0` on bodyless POSTs. 

@zachflower you're a man of HTTP/APIs... thoughts?

Tangentially related, we should be able to handle auth headers when the time comes in this SDK, but for now... we do not have any auth mechanisms yet.

2021-05-25 21:28 UTC, kyle-co commented on test/liqid_test.go
> +func Test_InitLiqidHostEnv(t *testing.T) {
This test exercises the ENV lookup for `LIQID_HOST`.

2021-05-26 15:58 UTC, marshall-mcmullen requested changes

2021-05-26 15:58 UTC, marshall-mcmullen commented on sshcontroller.go
> +	return &ssh, err
Yeah, probably better

2021-05-26 15:58 UTC, marshall-mcmullen commented on sshcontroller.go
> +	_, err = client.Do(req)
Curious, why do you ignore the response here ?

2021-05-26 15:58 UTC, marshall-mcmullen commented on systemcontroller.go
> +	STATERESET       = "/system/state/reset"
Just a style thing, but I prefer to not have the leading `/` on these URI components and at the call site using `%s/%s`. Partly the reason I prefer that is it lends itself to using things like go's built-in `filepath.Join` function instead of using fmt.Sprintf.

2021-05-26 15:58 UTC, marshall-mcmullen commented on systemcontroller.go
> +	_, err = client.Do(req)
Thanks for the comment. I would suggest embedding this comment into the code so others that weren't on this PR will know this too :-)

2021-05-26 15:58 UTC, marshall-mcmullen commented on systemcontroller.go
> +	req.Header.Set("Content-Length", "0")
Yes, I would definitely set it

2021-05-26 15:58 UTC, marshall-mcmullen commented on test/liqid_test.go
> +
Any time you create something that needs to be torn down, it's best to add a `defer` immediately after it is created to ensure it happens when you leave scope. That way you can't forget, and it won't be conditional if you leave the function early on an error, etc. so add a `defer gock.Off()` here and remove the explicit on on line 48

2021-05-26 15:58 UTC, marshall-mcmullen commented on test/liqid_test.go
> +	gock.Off()
move to defer

2021-05-26 15:58 UTC, marshall-mcmullen commented on test/liqid_test.go
> +	gock.Off()
move to defer

2021-05-26 15:58 UTC, marshall-mcmullen commented on test/liqid_test.go
> +	gock.Off()
move to defer

2021-05-26 15:58 UTC, marshall-mcmullen commented on test/sshcontroller_test.go
>  	liqidTestClient.Init()
I agree with the lint checks. You need to be asserting that `Init` succeeded

2021-05-26 16:18 UTC, kyle-co commented on test/liqid_test.go
> +
I actually cleaned this up in a local commit to use defer, will push. I had removed that idiom for some reason during debugging for a reason, but forgot to put it back.

2021-06-01 16:22 UTC, marshall-mcmullen approved these changes
Looks great! Looks like you addressed all my concerns. Thanks @kyle-co

2021-06-01 16:26 UTC, merged